spring:
  profiles:
    active: 
      - dev

---
spring:
   profiles: dev    #开发环境
   application:
      name: micservicecloud-config-dse-dev

---
spring:
    profies: test     #测试环境
    application:
        name: micservicecloud-config-dse-test

#请保存为UTF-8格式